# Generated by Django 5.1.1 on 2024-11-02 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('pet_art', models.CharField(max_length=100)),
                ('pet_weight', models.CharField(max_length=100)),
                ('pet_gender', models.CharField(max_length=50)),
                ('is_homeless', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='questions_files/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='questions.question')),
            ],
        ),
    ]
