# Generated by Django 5.1.1 on 2024-11-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
