# Generated by Django 5.1.1 on 2024-10-15 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vetbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=255)),
                ('animal_type', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('is_homeless', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('Male', 'Самец'), ('Female', 'Самка')], max_length=10)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='vetbook_photos/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='vetbook_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
