# Generated by Django 5.1.1 on 2024-11-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vetbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=255)),
                ('animal_type', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('is_homeless', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('Male', 'Самец'), ('Female', 'Самка')], max_length=10)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='vetbook_photos/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='vetbook_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chip_number', models.CharField(blank=True, max_length=50, null=True)),
                ('chip_install_date', models.DateField(blank=True, null=True)),
                ('chip_install_location', models.CharField(blank=True, max_length=255, null=True)),
                ('clinic', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('administration_date', models.DateField(blank=True, null=True)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('vetbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='vetbook.vetbook')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('deworming', 'Дегельминтизация'), ('ectoparasites', 'Обработка от эктопаразитов')], max_length=255)),
                ('medication_name', models.CharField(max_length=255)),
                ('treatment_date', models.DateField()),
                ('vetbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='vetbook.vetbook')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('missed_doses', models.CharField(blank=True, max_length=100, null=True)),
                ('calendar', models.TextField(blank=True, null=True)),
                ('vetbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_treatments', to='vetbook.vetbook')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255)),
                ('visit_date', models.DateField()),
                ('complaints', models.TextField(blank=True, null=True)),
                ('doctor_conclusion', models.TextField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='clinic_visits_files/')),
                ('vetbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_visits', to='vetbook.vetbook')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_date', models.DateField()),
                ('results', models.TextField(blank=True, null=True)),
                ('clinic', models.CharField(blank=True, max_length=255, null=True)),
                ('vetbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='vetbook.vetbook')),
            ],
        ),
    ]
